### ISSUE TITLE
Run the black console without error

### ISSUE THREAD

**Issue by codbish** [YHLpuyu/cesium_shine#1]
Hello, thank you very much for the code, give me a lot of inspiration; But I'm pulling your code locally now and it's running black and don't know how to start the sunshine analysis, thank you very much for the code and have a great day
<img width="799" alt="Snipaste_2023-10-23_21-33-59" src="https://github.com/YHLpuyu/cesium_shine/assets/101400112/ea4aba50-adfa-4a8b-81ed-9bcbc99302aa">

**Comment by YHLpuyu** [comment]
after you run `npm install`，you shoue modify `createUniformArray.js`. you can't push uniform array directly in cesium. please see this [article](https://blog.csdn.net/yue1241630499/article/details/132199878)

**Comment by YHLpuyu** [comment]
change function `UniformArrayFloatVec3.prototype.set` in createUniformArray.js, like below
```js
UniformArrayFloatVec3.prototype.set = function () {
  // enable push array to value
  const value = this.value instanceof Array?this.value:this.value.value;
  const length = value.length;
  const arraybuffer = this._value;
  let changed = false;
  let j = 0;

  for (let i = 0; i < length; ++i) {
    const v = value[i];

    if (defined(v.red)) {
      if (
        v.red !== arraybuffer[j] ||
        v.green !== arraybuffer[j + 1] ||
        v.blue !== arraybuffer[j + 2]
      ) {
        arraybuffer[j] = v.red;
        arraybuffer[j + 1] = v.green;
        arraybuffer[j + 2] = v.blue;
        changed = true;
      }
    } else if (defined(v.x)) {
      if (!Cartesian3.equalsArray(v, arraybuffer, j)) {
        Cartesian3.pack(v, arraybuffer, j);
        changed = true;
      }
    } else {
      //>>includeStart('debug', pragmas.debug);
      throw new DeveloperError("Invalid vec3 value.");
      //>>includeEnd('debug');
    }

    j += 3;
  }

  if (changed) {
    this._gl.uniform3fv(this._location, arraybuffer);
  }
};
```

**Comment by codbish** [comment]
Bro, it's a great honor that you helped with my problem, but after I changed the createUniformArray .js, it was still dark and I didn't know what the problem was

**Comment by YHLpuyu** [comment]
I try it again. Only need modify `UniformArrayFloatVec3.prototype.set`, in `/node_modules/@cesium/engine/Source/Renderer/createUniformArray.js`. Then run `npm run start` in terminal. You see below image.
![image](https://github.com/YHLpuyu/cesium_shine/assets/8923933/70fd9609-20c5-4263-8bbf-9aab7fb3a881)

**Comment by codbish** [comment]
It worked as you said, thanks
